config/routes.rb
Rails.application.routes.draw do
  shallow do
    resources :states do
      resources :breweries do
        resources :reviews
      end
    end
  end

end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
  belongs_to :state
  has_many :reviews

  validates :name, presence: true
  validates :location, presence: true
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :brewery

  validates :title, presence: :true
  validates :rating, inclusion: 0..5

end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :breweries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: [:show, :edit, :update, :destroy]

  # GET /breweries
  # GET /breweries.json
  def index
    @state = State.find(params[:state_id])
    @breweries = @state.breweries
  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
  end

  # GET /breweries/new
  def new
    @state = State.find(params[:state_id])
    @brewery = @state.breweries.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries
  # POST /breweries.json
  def create
    @brewery = Brewery.new(brewery_params)
    @brewery.state = State.find(params[:state_id])
    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1
  # PATCH/PUT /breweries/1.json
  def update
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    @brewery.destroy
    respond_to do |format|
      format.html { redirect_to breweries_url, notice: 'Brewery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_brewery
      @brewery = Brewery.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def brewery_params
      params.require(:brewery).permit(:name, :location, :url, :tours_?, :hours)
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # GET /reviews
  # GET /reviews.json
  def index
    @brewery = Brewery.find(params[:brewery_id])
    @reviews = @brewery.reviews
  end

  # POST /reviews
  # POST /reviews.json
  def create
      @brewery = Brewery.find(params[:brewery_id])
      @review = @brewery.reviews.create(review_params)
      redirect_to state_breweries_path(@brewery)
  end


  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: 'Review was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:title, :body, :rating, :brewery)
    end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController
  before_action :set_state, only: [:show, :edit, :update, :destroy]

  # GET /states
  # GET /states.json
  def index
    @states = State.all
  end

  # GET /states/1
  # GET /states/1.json
  def show
  end

  # GET /states/new
  def new
    @state = State.new
  end

  # GET /states/1/edit
  def edit
  end

  # POST /states
  # POST /states.json
  def create
    @state = State.new(state_params)

    respond_to do |format|
      if @state.save
        format.html { redirect_to @state, notice: 'State was successfully created.' }
        format.json { render :show, status: :created, location: @state }
      else
        format.html { render :new }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /states/1
  # PATCH/PUT /states/1.json
  def update
    respond_to do |format|
      if @state.update(state_params)
        format.html { redirect_to @state, notice: 'State was successfully updated.' }
        format.json { render :show, status: :ok, location: @state }
      else
        format.html { render :edit }
        format.json { render json: @state.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /states/1
  # DELETE /states/1.json
  def destroy
    @state.destroy
    respond_to do |format|
      format.html { redirect_to states_url, notice: 'State was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_state
      @state = State.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def state_params
      params.require(:state).permit(:name, :abrev)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/views/breweries/_form.html.erb
<%= form_for([@brewery.state, @state.breweries.build], html: {class: 'form-group'}) do |f| %>
  <% if @brewery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
      <% @brewery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name, class: 'col-sm-2 control-label' %><br>
      <div class="col-sm-10">
        <%= f.text_field :name %>
      </div>
  </div>
  <div class="field form-group">
    <%= f.label :location, class: 'col-sm-2 control-label' %><br>
      <div class="col-sm-10">
        <%= f.text_field :location %>
      </div>
  </div>
  <div class="field form-group">
    <%= f.label :url, class: 'col-sm-2 control-label' %><br>
      <div class="col-sm-10">
        <%= f.text_field :url %>
      </div>
  </div>
  <div class="field form-group">
    <%= f.label :tours_?, class: 'col-sm-2 control-label' %><br>
      <div class="col-sm-10">
        <%= f.check_box :tours_? %>
      </div>
  </div>
  <div class="field form-group">
    <%= f.label :hours, class: 'col-sm-2 control-label' %><br>
      <div class="col-sm-10">
        <%= f.text_field :hours %>
      </div>
  </div>

  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default"><%= f.submit %></button>
    </div>
  </div>
<% end %>

app/views/breweries/edit.html.erb
<div class="container">

<h1>Editing Brewery</h1>

<%= form_for(@brewery, html: {class: 'form-group'}) do |f| %>
  <% if @brewery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
      <% @brewery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :name, class: 'col-sm-2 control-label' %><br>
      <div class="col-sm-10">
        <%= f.text_field :name %>
      </div>
  </div>
  <div class="field form-group">
    <%= f.label :location, class: 'col-sm-2 control-label' %><br>
      <div class="col-sm-10">
        <%= f.text_field :location %>
      </div>
  </div>
  <div class="field form-group">
    <%= f.label :url, class: 'col-sm-2 control-label' %><br>
      <div class="col-sm-10">
        <%= f.text_field :url %>
      </div>
  </div>
  <div class="field form-group">
    <%= f.label :tours_?, class: 'col-sm-2 control-label' %><br>
      <div class="col-sm-10">
        <%= f.check_box :tours_? %>
      </div>
  </div>
  <div class="field form-group">
    <%= f.label :hours, class: 'col-sm-2 control-label' %><br>
      <div class="col-sm-10">
        <%= f.text_field :hours %>
      </div>
  </div>

  <div class="actions form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default"><%= f.submit %></button>
    </div>
  </div>
<% end %>

  <%= link_to state_breweries_path(:state_id), class: 'btn btn-danger' do %>
    <i class="glyphicon glyphicon-arrow-left"></i> Back
  <% end %>

</div>

app/views/breweries/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DrinkLocal</title>
  </head>

  <body>
    <div id="main-container" class="container-fluid">
      <div class="row">
        <div id="sidebar" class="col-xs-3">
          <!-- sidebar content -->
          <h1>Listing Breweries</h1>
        </div>
        <div id="main-content" class="col-xs-9">
          <!--  main content -->
          <table class = "table table-hover">
            <thead>
              <tr>
                <th>Name</th>
                <th>Location</th>
                <th>Url</th>
                <th colspan="3"></th>
              </tr>
            </thead>

            <tbody>
              <% @breweries.each do |brewery| %>
                <tr>
                  <td><%= brewery.name %></td>
                  <td><%= brewery.location %></td>
                  <td><%= brewery.url %></td>
                  <td><%= link_to 'Show', brewery, class: 'btn btn-default btn-sm' %></td>
                  <td><%= link_to 'Edit', edit_brewery_path(params[:brewery_id]), class: 'btn btn-default btn-sm' %></td>
                  <td><%= link_to 'Destroy', brewery, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger btn-sm' %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
          <%= link_to new_state_brewery_path, class: 'btn btn-success' do%>
            <i class="glyphicon glyphicon-plus"></i> New Brewery
          <%end%>
       </div>
      </div>
    </div>
  </body>
</html>

app/views/breweries/new.html.erb
<div class="container">
  <h1>New Brewery</h1>

  <%= render 'form' %>

  <%= link_to state_breweries_path(params[:state_id]), class: 'btn btn-danger' do %>
        <i class="glyphicon glyphicon-arrow-left"></i> Back
  <% end %>
</div>

app/views/breweries/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
  <div class="row clearfix">
    <div class="col-md-4 column">
      <img alt="140x140" src="http://lorempixel.com/140/140/" />
    </div>
    <div class="col-md-8 column">
      <h1>
        <%= @brewery.name %>
      </h1>
    </div>
  </div>
  <div class="row clearfix">
    <div class="col-md-4 column">
      <strong>Location:</strong>
      <%= @brewery.location %>
    </div>
    <div class="col-md-4 column">
      <strong>Url:</strong>
      <%= @brewery.url %>
    </div>
    <div class="col-md-4 column">
      <strong>Hours:</strong>
      <%= @brewery.hours %>
      <br>
      <strong>Tours ?:</strong>
      <%= @brewery.tours_? %>
    </div>
  </div>
  <div class="row clearfix">
    <div class="col-md-12 column">
     <strong>About:</strong>
     <%= @brewery.about %>
    </div>
  </div>
</div>
<div class="container">
  <div class="row clearfix">
    <div class="col-md-12 column">
      <h2 class="text-left">
        Reviews
      </h2>
    </div>
  </div>
  <div class="row clearfix">
  <% @brewery.reviews.each do |review| %>
      <div class="col-md-8 column">
        <strong>Title:</strong>
        <%= review.title %>
      </div>
      <div class="col-md-4 column">
        <strong>Rating:</strong>
        <%= "#{review.rating}/5" %>
      </div>
    </div>
    <div class="row clearfix">
      <div class="col-md-12 column">
        <strong>Review:</strong>
        <%= review.body %>
      </div>
    </div>
  <% end %>
  <div class="row clearfix">
    <div class="col-md-12 column">
      <h2 class="text-left">
      Add a review:
      </h2>
    </div>
  </div>
  <%= form_for([@brewery, @brewery.reviews.build],html: {class: 'form-group'}) do |f| %>
  <div class="row clearfix">
    <div class="col-md-12 column">
      <div class="field form-group">
        <%= f.label :title, class: 'col-sm-2 control-label' %><br>
      <div class="col-sm-10">
        <%= f.text_field :title %>
      </div>
      <div class="field form-group">
        <%= f.label :body, class: 'col-sm-2 control-label' %><br>
      <div class="col-sm-10">
        <%= f.text_field :body %>
      </div>
      <div class="field form-group">
        <%= f.label :rating, class: 'col-sm-2 control-label' %><br>
      <div class="col-sm-10">
        <%= f.text_field :rating %>
      </div>
      <div class="actions form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit %>
        </div>
      </div>

      </div>
    </div>
  </div>
  <% end %>

  <%= link_to state_breweries_path(:state_id), class: 'btn btn-danger' do %>
    <i class="glyphicon glyphicon-arrow-left"></i> Back
  <% end %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DrinkLocal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reviews/_form.html.erb
<%= form_for(@review) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h2>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :rating %><br>
    <%= f.number_field :rating %>
  </div>
  <div class="field">
    <%= f.label :brewery %><br>
    <%= f.text_field :brewery %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Rating</th>
      <th>Brewery</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reviews.each do |review| %>
      <tr>
        <td><%= review.title %></td>
        <td><%= review.body %></td>
        <td><%= review.rating %></td>
        <td><%= review.brewery %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Review', new_review_path %>

app/views/reviews/new.html.erb
<h1>New Review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @review.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @review.body %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @review.rating %>
</p>

<p>
  <strong>Brewery:</strong>
  <%= @review.brewery %>
</p>

<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>

app/views/states/_form.html.erb
<%= form_for(@state) do |f| %>
  <% if @state.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@state.errors.count, "error") %> prohibited this state from being saved:</h2>

      <ul>
      <% @state.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :abrev %><br>
    <%= f.text_field :abrev %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/states/edit.html.erb
<h1>Editing State</h1>

<%= render 'form' %>

<%= link_to 'Show', @state %> |
<%= link_to 'Back', states_path %>

app/views/states/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Listing States</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Abrev</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @states.each do |state| %>
      <tr>
        <td><%= state.name %></td>
        <td><%= state.abrev %></td>
        <td><%= link_to 'Breweries', state_breweries_path(state.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New State', new_state_path %>

app/views/states/new.html.erb
<h1>New State</h1>

<%= render 'form' %>

<%= link_to 'Back', states_path %>

app/views/states/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @state.name %>
</p>

<p>
  <strong>Abrev:</strong>
  <%= @state.abrev %>
</p>

<%= link_to 'Edit', edit_state_path(@state) %> |
<%= link_to 'Back', states_path %>